import { repository, transitionInvoice } from "../data/repository";
import type { ExceptionStatus, InvoiceStatus, RulesConfig } from "../domain/types";
import { storageAdapter } from "../adapters/storage";
import { assessInvoiceUpload } from "../engines/authenticity";

export const apService = {
  async dashboard() {
    const d=await repository.snapshot(); const invoices=d.invoices; const exceptions=d.exceptions.filter(x=>!["RESOLVED","APPROVED","REJECTED"].includes(x.status));
    const processed=invoices.filter(x=>!["RECEIVED","EXTRACTING","VALIDATING","MATCHING"].includes(x.status)); const touchless=processed.length ? processed.filter(x=>x.status==="AUTO_APPROVED").length/processed.length*100 : 0;
    const payable=invoices.filter(x=>["AUTO_APPROVED","APPROVED"].includes(x.status)).reduce((sum,x)=>sum+x.totalAmount,0);
    const byCategory=Object.entries(exceptions.reduce<Record<string,number>>((a,x)=>(a[x.category]=(a[x.category]??0)+1,a),{})).map(([category,count])=>({category,count}));
    return { kpis:{ totalInvoices:invoices.length,payableAmount:Math.round(payable*100)/100,openExceptions:exceptions.length,touchlessRate:Math.round(touchless*10)/10,averageCycleHours:3.8 },byCategory,recentInvoices:[...invoices].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,8) };
  },
  async invoices(query?: { status?: InvoiceStatus; supplierId?: string; search?: string }) { const d=await repository.snapshot(); return d.invoices.filter(x=>(!query?.status||x.status===query.status)&&(!query?.supplierId||x.supplierId===query.supplierId)&&(!query?.search||`${x.invoiceNumber} ${x.supplierName} ${x.poNumber??""}`.toLowerCase().includes(query.search.toLowerCase()))) },
  async invoicePage(query?: { status?: InvoiceStatus; search?: string; cursor?: string; limit?: number }) { const rows=await this.invoices(query); const limit=Math.min(Math.max(query?.limit??50,1),200); const start=query?.cursor ? Math.max(0,rows.findIndex(x=>x.id===query.cursor)+1) : 0; const items=rows.slice(start,start+limit); return {items,nextCursor:start+limit<rows.length?items.at(-1)?.id:null,total:rows.length,limit} },
  async ingestFile(input:{name:string;bytes:Uint8Array;contentType:string;orgId?:string}) { const d=await repository.snapshot(); const stored=await storageAdapter.save({name:input.name,bytes:input.bytes,contentType:input.contentType}); const assessment=assessInvoiceUpload(input); const now=new Date().toISOString(); const id=`inv_${crypto.randomUUID()}`; const invoice={id,orgId:input.orgId??d.organization.id,supplierName:"Unverified supplier",invoiceNumber:input.name.replace(/\.[^.]+$/,"").replace(/[^a-z0-9]+/gi,"-").toUpperCase().slice(0,32)||"UNVERIFIED",invoiceDate:now,dueDate:now,currency:"QAR",subtotal:0,taxAmount:0,totalAmount:0,sourceFileUrl:stored.url,sourceLanguage:"en" as const,rawExtraction:{language:"en" as const,overallConfidence:0,extractedAt:now,fields:{}},status:"EXCEPTION" as const,duplicateStatus:"NO_DUPLICATE" as const,lines:[],createdAt:now,updatedAt:now}; const exception={id:`exc_${crypto.randomUUID()}`,invoiceId:id,category:"SUPPLIER_ISSUE" as const,severity:assessment.risk==="HIGH"?"HIGH" as const:"MEDIUM" as const,aiAnalysis:`Unverified upload. ${assessment.reasons.join(" ")}`,aiRecommendation:"Verify the supplier against master data, confirm the PO and goods receipt independently, compare bank details, and obtain human approval before ERP posting.",aiConfidence:assessment.documentLike?.55:.2,status:"NEW" as const,createdAt:now,slaDueAt:new Date(Date.now()+2*60*60*1000).toISOString()}; await repository.addInvoice(invoice); await repository.addException(exception); await repository.addAudit({id:`audit_${crypto.randomUUID()}`,invoiceId:id,action:"AUTHENTICITY_REVIEW_REQUIRED",newStatus:"EXCEPTION",detail:{source:"UPLOAD",fileKey:stored.key,assessment},createdAt:now}); return {invoice,exception,authenticity:assessment} },
  async suppliers() { return (await repository.snapshot()).suppliers },
  async purchaseOrders() { return (await repository.snapshot()).purchaseOrders },
  async audit(invoiceId?:string) { const rows=(await repository.snapshot()).auditLogs; return rows.filter(row=>!invoiceId||row.invoiceId===invoiceId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)) },
  async assignException(id:string,userId:string) { const d=await repository.snapshot(); const assignee=d.users.find(user=>user.id===userId); if(!assignee)throw new Error("Assignee not found"); return repository.updateException(id,{assignedToId:userId,status:"UNDER_REVIEW"}) },
  async invoice(id:string) { const d=await repository.snapshot(); const invoice=d.invoices.find(x=>x.id===id); if(!invoice)return null; return {invoice,supplier:d.suppliers.find(x=>x.id===invoice.supplierId),purchaseOrder:d.purchaseOrders.find(x=>x.poNumber===invoice.poNumber),goodsReceipt:d.goodsReceipts.find(g=>g.poId===d.purchaseOrders.find(p=>p.poNumber===invoice.poNumber)?.id),exception:d.exceptions.find(x=>x.invoiceId===id),audit:d.auditLogs.filter(x=>x.invoiceId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))} },
  async exceptions() { const d=await repository.snapshot(); return d.exceptions.map(x=>({...x,invoice:d.invoices.find(i=>i.id===x.invoiceId)!})).sort((a,b)=>a.slaDueAt.localeCompare(b.slaDueAt)) },
  async decide(input:{invoiceId:string;exceptionId?:string;decision:"APPROVE"|"REJECT"|"REQUEST_INFO";userId:string;note?:string}) { const status:InvoiceStatus=input.decision==="APPROVE"?"APPROVED":input.decision==="REJECT"?"REJECTED":"EXCEPTION"; const invoice=await transitionInvoice(input.invoiceId,status,input.userId,{decision:input.decision,note:input.note,humanDecision:true}); if(input.exceptionId){const exceptionStatus:ExceptionStatus=input.decision==="APPROVE"?"APPROVED":input.decision==="REJECT"?"REJECTED":"WAITING_FOR_INFO"; await repository.updateException(input.exceptionId,{status:exceptionStatus})} return invoice },
  async rules() { return (await repository.snapshot()).rules },
  async updateRules(patch:Partial<RulesConfig>) { return repository.updateRules(patch) },
  async resetDemo() { await repository.reset() }
};
