"use client";

import { useMemo, useState } from "react";
import type { AppData, Invoice, InvoiceStatus, Role, RulesConfig } from "@/lib/domain/types";
import { Activity, AlertTriangle, Bell, Bot, Check, ChevronLeft, CircleDollarSign, Clock3, FileCheck2, FileSearch, Files, Gauge, Inbox, LayoutDashboard, Menu, MoreHorizontal, Plus, RotateCcw, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Upload, UserRoundCheck, X } from "lucide-react";

type View = "dashboard" | "operations" | "workflow" | "invoices" | "exceptions" | "rules" | "invoice";
const money = (value:number) => new Intl.NumberFormat("en-QA", { style:"currency", currency:"QAR", maximumFractionDigits:0 }).format(value);
const date = (value:string) => new Intl.DateTimeFormat("en-GB", { day:"2-digit", month:"short", year:"numeric" }).format(new Date(value));
const statusLabel = (status:string) => status.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, c => c.toUpperCase());
const badgeClass = (status:string) => ["AUTO_APPROVED","APPROVED","RESOLVED","ACTIVE"].includes(status) ? "success" : ["EXCEPTION","WAITING_FOR_INFO","UNDER_REVIEW"].includes(status) ? "warning" : ["REJECTED","HIGH","CONFIRMED_DUPLICATE"].includes(status) ? "danger" : "neutral";

export function CommandCenter({ initialData }: { initialData: AppData }) {
  const [data, setData] = useState(initialData);
  const [view, setView] = useState<View>("dashboard");
  const [selectedId, setSelectedId] = useState<string>("inv_010");
  const [role, setRole] = useState<Role>("AP_MANAGER");
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("ALL");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [toast, setToast] = useState("");
  const [uploadOpen, setUploadOpen] = useState(false);
  const [uploadStage, setUploadStage] = useState(-1);
  const [uploadName, setUploadName] = useState("");
  const [notificationsOpen, setNotificationsOpen] = useState(false);

  const metrics = useMemo(() => {
    const processed = data.invoices.filter(i => !["RECEIVED","EXTRACTING","VALIDATING","MATCHING"].includes(i.status));
    const payable = data.invoices.filter(i => ["AUTO_APPROVED","APPROVED"].includes(i.status)).reduce((s,i)=>s+i.totalAmount,0);
    const open = data.exceptions.filter(e => !["RESOLVED","APPROVED","REJECTED"].includes(e.status));
    const touchless = processed.length ? processed.filter(i=>i.status === "AUTO_APPROVED").length / processed.length * 100 : 0;
    return { total:data.invoices.length, payable, open:open.length, touchless };
  }, [data]);
  const selected = data.invoices.find(i=>i.id===selectedId) ?? data.invoices[0];
  const exception = data.exceptions.find(e=>e.invoiceId===selected?.id);
  const user = role === "AP_CLERK" ? data.users[0] : role === "AUDITOR" ? data.users[2] : data.users[1];
  const canDecide = role === "AP_MANAGER" || role === "FINANCE_MANAGER" || role === "ADMIN";

  function navigate(next:View) { setView(next); setMobileOpen(false); window.scrollTo({top:0,behavior:"smooth"}); }
  function openInvoice(id:string) { setSelectedId(id); navigate("invoice"); }
  function notify(message:string) { setToast(message); window.setTimeout(()=>setToast(""),2600); }
  function decide(status:InvoiceStatus, label:string) {
    setData(current=>({...current,invoices:current.invoices.map(i=>i.id===selected.id?{...i,status,updatedAt:new Date().toISOString()}:i),exceptions:current.exceptions.map(e=>e.invoiceId===selected.id?{...e,status:status==="APPROVED"?"APPROVED":status==="REJECTED"?"REJECTED":"WAITING_FOR_INFO"}:e),auditLogs:[...current.auditLogs,{id:`audit_${Date.now()}`,invoiceId:selected.id,userId:user.id,action:`HUMAN_${label.toUpperCase().replaceAll(" ","_")}`,previousStatus:selected.status,newStatus:status,detail:{humanDecision:true,role},createdAt:new Date().toISOString()}]}));
    notify(`Invoice ${label.toLowerCase()} and audit record created.`);
  }
  function updateRule(key:keyof RulesConfig,value:number|boolean) { setData(d=>({...d,rules:{...d.rules,[key]:value}})); }
  function reprocessInvoice() { const priceIssue=selected.id==="inv_010"; const passes=!priceIssue||data.rules.priceTolerancePercent>=7.5; const next:InvoiceStatus=passes?"AUTO_APPROVED":"EXCEPTION"; setData(current=>({...current,invoices:current.invoices.map(i=>i.id===selected.id?{...i,status:next,updatedAt:new Date().toISOString()}:i),auditLogs:[...current.auditLogs,{id:`audit_reprocess_${Date.now()}`,invoiceId:selected.id,userId:user.id,action:"INVOICE_REPROCESSED",previousStatus:selected.status,newStatus:next,detail:{rulesVersion:4,priceTolerance:data.rules.priceTolerancePercent},createdAt:new Date().toISOString()}]})); notify(passes?"Reprocessing complete — invoice is now eligible for auto-approval.":"Reprocessing complete — the variance still requires review."); }
  function simulateEmailIntake() { const source=data.invoices[2];const now=new Date().toISOString();const id=`inv_email_${Date.now()}`;const added={...source,id,invoiceNumber:`EMAIL-${String(Date.now()).slice(-6)}`,status:"RECEIVED" as InvoiceStatus,createdAt:now,updatedAt:now};setData(current=>({...current,invoices:[added,...current.invoices],auditLogs:[...current.auditLogs,{id:`audit_email_${Date.now()}`,invoiceId:id,action:"INVOICE_RECEIVED",newStatus:"RECEIVED",detail:{channel:"EMAIL",mailbox:"ap@alrayyan.qa"},createdAt:now}]}));notify("Email intake received from ap@alrayyan.qa and queued for extraction."); }
  async function ingest(file:File) {
    setUploadName(file.name); setUploadStage(0);
    for (let stage=1; stage<5; stage++) { await new Promise(resolve=>window.setTimeout(resolve,520)); setUploadStage(stage); }
    const source=data.invoices.find(i=>i.status==="AUTO_APPROVED") ?? data.invoices[0]; const now=new Date().toISOString(); const id=`inv_upload_${Date.now()}`;
    const added:Invoice={...source,id,invoiceNumber:file.name.replace(/\.[^.]+$/,"").toUpperCase().replace(/[^A-Z0-9]+/g,"-").slice(0,18),sourceFileUrl:URL.createObjectURL(file),status:"AUTO_APPROVED",createdAt:now,updatedAt:now,rawExtraction:{...source.rawExtraction,extractedAt:now}};
    setData(current=>({...current,invoices:[added,...current.invoices],auditLogs:[...current.auditLogs,{id:`audit_${Date.now()}`,invoiceId:id,action:"RULES_PASSED",previousStatus:"MATCHING",newStatus:"AUTO_APPROVED",detail:{deterministic:true,source:"UPLOAD"},createdAt:now}]}));
    await new Promise(resolve=>window.setTimeout(resolve,450)); setUploadOpen(false); setUploadStage(-1); setSelectedId(id); setView("invoice"); notify("Invoice processed and auto-approved in 3.1 seconds.");
  }

  return <div className="app-grid">
    <aside className={`sidebar ${mobileOpen?"open":""}`}>
      <div className="brand"><span className="brand-mark">NX</span><span>Nexa AP</span></div>
      <div className="org-label">Workspace</div>
      <nav className="nav" aria-label="Primary navigation">
        <Nav active={view==="dashboard"} icon={<LayoutDashboard size={16}/>} label="Command center" onClick={()=>navigate("dashboard")}/>
        <Nav active={view==="operations"} icon={<Activity size={16}/>} label="Processing control" onClick={()=>navigate("operations")}/>
        <Nav active={view==="workflow"} icon={<CircleDollarSign size={16}/>} label="How it works" onClick={()=>navigate("workflow")}/>
        <Nav active={view==="invoices"||view==="invoice"} icon={<Inbox size={16}/>} label="Invoice inbox" onClick={()=>navigate("invoices")}/>
        <Nav active={view==="exceptions"} icon={<AlertTriangle size={16}/>} label="Exceptions" count={metrics.open} onClick={()=>navigate("exceptions")}/>
        <Nav active={view==="rules"} icon={<Settings2 size={16}/>} label="Rules & controls" onClick={()=>navigate("rules")}/>
      </nav>
      <div className="sidebar-bottom"><div className="health"><span className="health-dot"/>All systems operational</div><div className="profile"><span className="avatar">{user.initials}</span><div><strong>{user.name}</strong><span>{statusLabel(role)}</span></div></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="crumb"><button className="icon-btn mobile-menu" aria-label="Open navigation" onClick={()=>setMobileOpen(v=>!v)}><Menu size={16}/></button><span>Al Rayyan Trading</span><span>/</span><strong>{view==="invoice"?selected.invoiceNumber:statusLabel(view)}</strong></div><div className="top-actions"><select className="select role-select" aria-label="Demo persona" value={role} onChange={e=>setRole(e.target.value as Role)}><option value="AP_CLERK">AP Clerk</option><option value="AP_MANAGER">AP Manager</option><option value="AUDITOR">Auditor</option></select><button className="icon-btn notification-button" aria-label="Notifications" onClick={()=>setNotificationsOpen(v=>!v)}><Bell size={15}/><span/></button></div></header>
      <div className="content">
        {view==="dashboard"&&<Dashboard data={data} metrics={metrics} onInvoices={()=>navigate("invoices")} onExceptions={()=>navigate("exceptions")} onOpen={openInvoice}/>} 
        {view==="operations"&&<Operations/>}
        {view==="workflow"&&<HowItWorks/>}
        {view==="invoices"&&<Invoices data={data} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} onOpen={openInvoice} onUpload={()=>setUploadOpen(true)} onEmail={simulateEmailIntake}/>} 
        {view==="exceptions"&&<Exceptions data={data} onOpen={openInvoice}/>} 
        {view==="rules"&&<Rules rules={data.rules} role={role} updateRule={updateRule} onSave={()=>notify("Rules version 4 saved. New invoices will use these tolerances.")}/>} 
        {view==="invoice"&&<InvoiceDetail invoice={selected} data={data} exception={exception} canDecide={canDecide} onBack={()=>navigate("invoices")} decide={decide} onReprocess={reprocessInvoice}/>} 
      </div>
    </main>
    {toast&&<div className="toast" role="status">{toast}</div>}
    {uploadOpen&&<UploadDialog stage={uploadStage} fileName={uploadName} onClose={()=>{if(uploadStage<0)setUploadOpen(false)}} onFile={ingest}/>} 
    {notificationsOpen&&<div className="notification-panel"><div className="panel-head"><h2>Notifications</h2><button onClick={()=>setNotificationsOpen(false)}>Close</button></div><div className="notice unread"><AlertTriangle size={14}/><div><strong>2 high-risk exceptions approach SLA</strong><span>Review before 17:00 today</span></div></div><div className="notice"><FileCheck2 size={14}/><div><strong>Overnight batch completed</strong><span>2,142 invoices · 94.8% touchless</span></div></div><div className="notice"><ShieldCheck size={14}/><div><strong>Rules version 3 remains active</strong><span>No control changes in the last 24 hours</span></div></div></div>}
  </div>;
}

function Nav({active,icon,label,count,onClick}:{active:boolean;icon:React.ReactNode;label:string;count?:number;onClick:()=>void}) { return <button className={active?"active":""} onClick={onClick}>{icon}<span>{label}</span>{count!==undefined&&<span className="nav-count">{count}</span>}</button> }

function Dashboard({data,metrics,onInvoices,onExceptions,onOpen}:{data:AppData;metrics:{total:number;payable:number;open:number;touchless:number};onInvoices:()=>void;onExceptions:()=>void;onOpen:(id:string)=>void}) {
  const bars=[58,65,63,72,68,79,75,81,78,86,84,88]; const processed=[48,55,52,61,58,69,65,72,70,78,76,81];
  const cats=data.exceptions.reduce<Record<string,number>>((a,e)=>(a[e.category]=(a[e.category]||0)+1,a),{}); const max=Math.max(...Object.values(cats));
  return <><div className="page-head"><div><div className="eyebrow">Tuesday, 11 August · Doha</div><h1>Good evening, Omar.</h1><p className="subtitle">A clear view of what moved, what stopped, and what needs your judgment.</p></div><button className="btn btn-primary" onClick={onInvoices}><Plus size={14}/>Process invoice</button></div>
    <section className="daily-brief"><div className="brief-mark"><span>05</span><small>open</small></div><div className="brief-copy"><span>Today’s control note</span><strong>Two invoices need a decision before close of business.</strong><p>The nearest SLA is a PO price variance from Hilti Qatar. Three lower-risk cases can wait until tomorrow.</p></div><div className="brief-deadline"><Clock3 size={15}/><div><small>Nearest SLA</small><strong>2h 14m</strong></div></div><button className="brief-action" onClick={onExceptions}>Review the queue <span>→</span></button></section>
    <section className="kpi-grid"><Kpi icon={<Files size={14}/>} label="Invoices processed" value={metrics.total.toString()} foot="↑ 8.4%" note="vs last month"/><Kpi icon={<CircleDollarSign size={14}/>} label="Approved payable" value={money(metrics.payable)} foot="QAR" note="ready for ERP posting"/><Kpi icon={<AlertTriangle size={14}/>} label="Open exceptions" value={metrics.open.toString()} foot="2 high" note="require attention"/><Kpi icon={<Gauge size={14}/>} label="Touchless rate" value={`${metrics.touchless.toFixed(1)}%`} foot="↑ 3.2%" note="automation rate"/></section>
    <section className="dashboard-grid"><div className="card"><div className="panel-head"><h2>Processing & touchless performance</h2><span>Last 12 weeks</span></div><div className="chart-area">{bars.map((b,i)=><div className="bar-wrap" key={i}><div className="bar-pair"><div className="bar" style={{height:`${processed[i]}%`}}/><div className="bar accent" style={{height:`${b}%`}}/></div><span className="bar-label">W{i+1}</span></div>)}</div><div className="legend"><span><i style={{background:"#bfd0c8"}}/>Invoices</span><span><i style={{background:"#176b51"}}/>Touchless</span></div></div>
      <div className="card"><div className="panel-head"><h2>Exceptions by reason</h2><button onClick={onInvoices}>View queue</button></div><div className="exception-stack">{Object.entries(cats).map(([cat,n])=><div className="exception-row" key={cat}><strong>{statusLabel(cat)}</strong><span>{n}</span><div className="progress"><div style={{width:`${n/max*100}%`}}/></div></div>)}</div></div>
      <div className="card recent"><div className="panel-head"><h2>Recent activity</h2><button onClick={onInvoices}>View all invoices</button></div><InvoiceTable invoices={[...data.invoices].reverse().slice(0,6)} onOpen={onOpen}/></div></section></>;
}

function Kpi({icon,label,value,foot,note}:{icon:React.ReactNode;label:string;value:string;foot:string;note:string}) { return <div className="card kpi"><div className="kpi-top"><span>{label}</span><span className="kpi-icon">{icon}</span></div><div className="kpi-value">{value}</div><div className="kpi-foot"><span className="trend">{foot}</span><span>{note}</span></div></div> }

function Operations() {
  const lanes=[{name:"Email intake",value:3210,state:"Healthy"},{name:"Portal uploads",value:4784,state:"Healthy"},{name:"SFTP batches",value:1848,state:"Healthy"}];
  const runs=[{id:"RUN-0811-04",source:"Supplier portal",received:2500,completed:2318,exceptions:118,status:"Processing",started:"14:05"},{id:"RUN-0811-03",source:"Email inbox",received:3000,completed:3000,exceptions:164,status:"Complete",started:"10:30"},{id:"RUN-0811-02",source:"ERP document drop",received:2200,completed:2200,exceptions:97,status:"Complete",started:"07:15"},{id:"RUN-0811-01",source:"Overnight SFTP",received:2142,completed:2142,exceptions:112,status:"Complete",started:"01:00"}];
  return <><div className="page-head"><div><div className="eyebrow">High-volume operations · 11 August</div><h1>Processing control</h1><p className="subtitle">Manage the flow, not ten thousand individual rows.</p></div><span className="capacity-chip"><span/>Within capacity · 41%</span></div>
    <section className="volume-hero"><div><span>Received today</span><strong>9,842</strong><small>across 4 controlled runs</small></div><div><span>Decisions completed</span><strong>9,660</strong><small>98.2% cleared automatically or routed</small></div><div><span>In progress</span><strong>182</strong><small>estimated clearance in 7 minutes</small></div><div><span>Design capacity</span><strong>24k</strong><small>invoices per business day</small></div></section>
    <section className="ops-grid"><div className="card queue-card"><div className="panel-head"><h2>Live processing lanes</h2><span>Updated just now</span></div><div className="lane-list">{lanes.map((lane,i)=><div className="lane" key={lane.name}><div className="lane-name"><span className="lane-pulse"/><div><strong>{lane.name}</strong><small>{lane.value.toLocaleString()} documents today</small></div></div><div className="lane-track"><i style={{width:`${[72,88,54][i]}%`}}/></div><span className="lane-rate">{[41,67,29][i]}/min</span><span className="lane-state">{lane.state}</span></div>)}</div></div>
      <div className="card pressure-card"><div className="panel-head"><h2>Queue pressure</h2><span>Auto-balancing</span></div><div className="pressure-body"><div className="pressure-ring"><strong>41%</strong><span>capacity</span></div><div className="pressure-notes"><p><span className="success-dot"/>Extraction <strong>68 waiting</strong></p><p><span className="success-dot"/>Matching <strong>92 waiting</strong></p><p><span className="warn-dot"/>Investigation <strong>22 waiting</strong></p></div></div><div className="ops-note"><ShieldCheck size={14}/><span>Every document uses an idempotency key. Retries cannot create duplicate invoices.</span></div></div>
      <div className="card run-table"><div className="panel-head"><h2>Today’s processing runs</h2><button>Export operations log</button></div><div className="table-scroll"><table><thead><tr><th>Run</th><th>Source</th><th>Started</th><th>Progress</th><th>Exceptions</th><th>Status</th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td className="primary-cell">{run.id}</td><td>{run.source}</td><td>{run.started}</td><td><div className="run-progress"><span><i style={{width:`${run.completed/run.received*100}%`}}/></span><small>{run.completed.toLocaleString()} / {run.received.toLocaleString()}</small></div></td><td>{run.exceptions}</td><td><span className={`badge ${run.status==="Complete"?"success":"warning"}`}>{run.status}</span></td></tr>)}</tbody></table></div></div>
    </section><div className="scale-guidance"><Bot size={16}/><div><strong>How people work at this volume</strong><p>Clerks work saved exception views and assigned batches; managers monitor SLA and queue pressure. Individual invoices remain available for investigation, but nobody scrolls through 10,000 rows.</p></div></div></>;
}

function HowItWorks() {
  const stages=[{n:"01",title:"Invoice arrives",company:"AP receives one normalized record from upload or the shared mailbox.",supplier:"Supplier sends its normal PDF—no new system or format is required."},{n:"02",title:"Evidence is checked",company:"Supplier master, duplicate, PO, GRN, price and quantity controls run automatically.",supplier:"Fewer repetitive emails asking for references already present on the document."},{n:"03",title:"A clear outcome",company:"Clean invoices move forward; ambiguous invoices enter a prioritized human queue.",supplier:"Problems are identified early with a specific reason instead of an unexplained payment delay."},{n:"04",title:"Human resolution",company:"An authorized person approves, rejects or requests information with evidence and an audit record.",supplier:"The request names exactly what is missing, reducing back-and-forth and resubmission time."}];
  return <><div className="page-head"><div><div className="eyebrow">One invoice · two experiences</div><h1>How the system works</h1><p className="subtitle">A faster control process for the company and a more predictable experience for its suppliers.</p></div><span className="badge neutral">MVP operating model</span></div>
    <section className="problem-statement"><div className="problem-label">The problem</div><div><strong>Invoice processing breaks when evidence lives across inboxes, spreadsheets and ERP screens.</strong><p>AP teams spend their time finding documents and explaining delays. Suppliers cannot see why an invoice is held, so they call or email repeatedly. Managers receive problems late, while duplicate payments, unmatched receipts and weak audit evidence remain financial risks.</p></div><div className="problem-metrics"><span><strong>10k</strong> daily documents</span><span><strong>6+</strong> manual handoffs</span><span><strong>1</strong> controlled record</span></div></section>
    <div className="sides-head"><div><span className="side-icon company"><ShieldCheck size={16}/></span><div><small>Company side</small><strong>Accounts payable team</strong></div></div><div className="shared-label">Shared invoice lifecycle</div><div><span className="side-icon supplier"><Files size={16}/></span><div><small>Supplier side</small><strong>Invoice sender</strong></div></div></div>
    <section className="two-side-flow">{stages.map(stage=><div className="flow-row" key={stage.n}><div className="side-copy company-copy"><span>Company</span><p>{stage.company}</p></div><div className="flow-center"><i>{stage.n}</i><strong>{stage.title}</strong></div><div className="side-copy supplier-copy"><span>Supplier</span><p>{stage.supplier}</p></div></div>)}</section>
    <section className="outcome-grid"><div><span>Speed</span><strong>Seconds instead of days</strong><p>Clean invoices pass without human touch; staff focus only on genuine exceptions.</p></div><div><span>Trust</span><strong>Every decision has evidence</strong><p>Rules, matched documents, AI guidance and human actions remain visible in one audit chain.</p></div><div><span>Control</span><strong>Automation never removes authority</strong><p>AI explains ambiguity. Deterministic rules control routing. People retain financial approval.</p></div></section>
    <div className="scope-note"><AlertTriangle size={15}/><div><strong>Supplier-side scope</strong><p>The MVP improves the supplier experience through clearer email requests and faster resolution. A self-service supplier portal remains a future extension, not a hidden dependency of this workflow.</p></div></div></>;
}

function Invoices({data,search,setSearch,filter,setFilter,onOpen,onUpload,onEmail}:{data:AppData;search:string;setSearch:(s:string)=>void;filter:string;setFilter:(s:string)=>void;onOpen:(id:string)=>void;onUpload:()=>void;onEmail:()=>void}) {
  const list=data.invoices.filter(i=>(filter==="ALL"||i.status===filter)&&(`${i.invoiceNumber} ${i.supplierName} ${i.poNumber}`.toLowerCase().includes(search.toLowerCase())));
  return <><div className="page-head"><div><div className="eyebrow">Invoice operations</div><h1>Invoice inbox</h1><p className="subtitle">Every invoice, from receipt to final decision.</p></div><button className="btn btn-primary" onClick={onUpload}><Upload size={14}/>Upload invoice</button></div><div className="toolbar"><div className="search"><Search size={14}/><input className="input" aria-label="Search invoices" placeholder="Search invoice, supplier or PO…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All statuses</option><option value="RECEIVED">Received</option><option value="AUTO_APPROVED">Auto-approved</option><option value="EXCEPTION">Exceptions</option><option value="APPROVED">Approved</option></select><button className="btn" onClick={onEmail}><Inbox size={13}/>Simulate email intake</button></div><div className="card table-card">{list.length?<InvoiceTable invoices={list} onOpen={onOpen}/>:<Empty/>}</div></>;
}

function InvoiceTable({invoices,onOpen}:{invoices:Invoice[];onOpen:(id:string)=>void}) { return <div className="table-scroll"><table><thead><tr><th>Invoice</th><th>Supplier</th><th>PO reference</th><th>Date</th><th>Status</th><th style={{textAlign:"right"}}>Amount</th><th/></tr></thead><tbody>{invoices.map(i=><tr key={i.id} onClick={()=>onOpen(i.id)}><td className="primary-cell">{i.invoiceNumber}<span className="secondary-cell">{i.sourceLanguage==="ar"?"Arabic document":"Uploaded PDF"}</span></td><td>{i.supplierName}</td><td>{i.poNumber??<span style={{color:"#b43a3a"}}>Missing</span>}</td><td>{date(i.invoiceDate)}</td><td><span className={`badge ${badgeClass(i.status)}`}>{statusLabel(i.status)}</span></td><td className="amount">{money(i.totalAmount)}</td><td><MoreHorizontal size={15} color="#83908a"/></td></tr>)}</tbody></table></div> }

function Exceptions({data,onOpen}:{data:AppData;onOpen:(id:string)=>void}) { const items=data.exceptions.map(e=>({...e,invoice:data.invoices.find(i=>i.id===e.invoiceId)!})).filter(e=>!["APPROVED","REJECTED","RESOLVED"].includes(e.status)); return <><div className="page-head"><div><div className="eyebrow">Human review</div><h1>Exception queue</h1><p className="subtitle">Prioritized by severity and service-level deadline.</p></div><button className="btn"><UserRoundCheck size={14}/>Assign selected</button></div><div className="toolbar"><button className="btn btn-primary">All open <span>{items.length}</span></button><button className="btn">High severity</button><button className="btn">Waiting for info</button></div><div className="card table-card"><div className="table-scroll"><table><thead><tr><th>Severity</th><th>Invoice</th><th>Exception</th><th>AI confidence</th><th>SLA</th><th>Status</th><th style={{textAlign:"right"}}>Amount</th></tr></thead><tbody>{items.map(e=><tr key={e.id} onClick={()=>onOpen(e.invoiceId)}><td><span className={`badge ${badgeClass(e.severity)}`}>{e.severity}</span></td><td className="primary-cell">{e.invoice.invoiceNumber}<span className="secondary-cell">{e.invoice.supplierName}</span></td><td>{statusLabel(e.category)}</td><td>{Math.round((e.aiConfidence??0)*100)}%</td><td><span style={{color:e.severity==="HIGH"?"#b43a3a":"inherit",fontWeight:650}}>{e.severity==="HIGH"?"2h 14m":"18h 40m"}</span></td><td><span className={`badge ${badgeClass(e.status)}`}>{statusLabel(e.status)}</span></td><td className="amount">{money(e.invoice.totalAmount)}</td></tr>)}</tbody></table></div></div></> }

function InvoiceDetail({invoice,data,exception,canDecide,onBack,decide,onReprocess}:{invoice:Invoice;data:AppData;exception:AppData["exceptions"][number]|undefined;canDecide:boolean;onBack:()=>void;decide:(s:InvoiceStatus,l:string)=>void;onReprocess:()=>void}) {
  const po=data.purchaseOrders.find(p=>p.poNumber===invoice.poNumber); const grn=data.goodsReceipts.find(g=>g.poId===po?.id); const audits=data.auditLogs.filter(a=>a.invoiceId===invoice.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); const conf=invoice.rawExtraction.overallConfidence;
  return <><div className="page-head"><div><button className="btn" onClick={onBack} style={{marginBottom:14}}><ChevronLeft size={14}/>Back to inbox</button><div className="eyebrow">{invoice.supplierName}</div><h1>{invoice.invoiceNumber}</h1><p className="subtitle">Received {date(invoice.createdAt)} · {invoice.sourceLanguage==="ar"?"Arabic":"English"} · {money(invoice.totalAmount)}</p></div><div className="detail-actions"><span className={`badge ${badgeClass(invoice.status)}`}>{statusLabel(invoice.status)}</span><button className="btn" onClick={onReprocess}><RotateCcw size={13}/>Re-run controls</button></div></div>
    <div className="detail-grid"><div className="card pipeline"><div className="pipeline-top"><h2>Processing pipeline</h2><span className="badge neutral"><Activity size={10}/>Completed in 43 sec</span></div><div className="pipeline-stages">{["Received","Extracted","Validated","Matched",invoice.status==="EXCEPTION"?"Exception":"Decision"].map((s,i)=><div className="stage done" style={{animationDelay:`${i*.1}s`}} key={s}><span className="stage-dot"><Check size={12}/></span><span>{s}</span></div>)}</div></div>
      <div className="card"><div className="panel-head"><h2>Source document</h2><span className="language">{invoice.sourceLanguage.toUpperCase()}</span></div><div className="doc-preview"><div className="invoice-paper" dir={invoice.sourceLanguage==="ar"?"rtl":"ltr"}><div className="paper-logo">{invoice.supplierName.toUpperCase()}</div><div className="paper-title">{invoice.sourceLanguage==="ar"?"فاتورة ضريبية":"TAX INVOICE"}</div><div className="paper-meta"><span>{invoice.invoiceNumber}</span><span>{invoice.invoiceDate}</span><span>{invoice.poNumber??"No PO reference"}</span><span>{invoice.currency}</span></div><div className="paper-lines">{invoice.lines.map(l=><div className="paper-line" key={l.id}><span>{l.description}</span><strong>{money(l.quantity*l.unitPrice)}</strong></div>)}</div><div className="paper-total">TOTAL&nbsp;&nbsp; {money(invoice.totalAmount)}</div></div></div></div>
      <div style={{display:"grid",gap:16}}><div className="card"><div className="panel-head"><h2>Extracted fields</h2><span>{Math.round(conf*100)}% confidence</span></div><div className="section-body fields"><Field label="Supplier" value={invoice.supplierName} confidence={conf}/><Field label="Invoice number" value={invoice.invoiceNumber} confidence={conf}/><Field label="PO reference" value={invoice.poNumber??"Not detected"} confidence={invoice.poNumber?conf:.34}/><Field label="Invoice total" value={money(invoice.totalAmount)} confidence={Math.min(.99,conf+.02)}/><Field label="Due date" value={date(invoice.dueDate)} confidence={conf}/></div></div>
        <div className="card"><div className="panel-head"><h2>Document matching</h2><span>{grn?"3-way match":"2-way match"}</span></div><div className="section-body fields"><Field label="Purchase order" value={po?.poNumber??"Not found"} confidence={po?1:0}/><Field label="Goods receipt" value={grn?.grnNumber??"Not found"} confidence={grn?1:0}/><Field label="Supplier master" value={invoice.supplierId?"Validated":"Unknown supplier"} confidence={invoice.supplierId?1:0}/><Field label="Duplicate check" value={statusLabel(invoice.duplicateStatus)} confidence={invoice.duplicateStatus==="NO_DUPLICATE"?1:.5}/></div></div></div>
      <div className="card comparison-card"><div className="panel-head"><h2>Line-level evidence</h2><span>Invoice ↔ PO ↔ GRN</span></div><div className="table-scroll"><table><thead><tr><th>Description</th><th>Invoice qty</th><th>Received qty</th><th>Invoice price</th><th>PO price</th><th>Result</th></tr></thead><tbody>{invoice.lines.map((line,i)=>{const poLine=po?.lines[i];const grnLine=grn?.lines[i];const priceOk=!poLine||Math.abs(line.unitPrice-poLine.unitPrice)/poLine.unitPrice*100<=data.rules.priceTolerancePercent;const qtyOk=!grnLine||line.quantity<=grnLine.quantityReceived*(1+data.rules.quantityTolerancePercent/100);return <tr key={line.id}><td className="primary-cell">{line.description}</td><td>{line.quantity}</td><td>{grnLine?.quantityReceived??"—"}</td><td>{money(line.unitPrice)}</td><td>{poLine?money(poLine.unitPrice):"—"}</td><td><span className={`badge ${priceOk&&qtyOk?"success":"danger"}`}>{priceOk&&qtyOk?"Within control":"Variance"}</span></td></tr>})}</tbody></table></div></div>
      <details className="card raw-panel"><summary><span><FileSearch size={14}/>Raw extraction payload</span><small>Debug evidence · read only</small></summary><pre>{JSON.stringify(invoice.rawExtraction,null,2)}</pre></details>
      {exception&&<div className="card"><div className="panel-head"><h2>Exception investigation</h2><span className={`badge ${badgeClass(exception.severity)}`}>{exception.severity}</span></div><div className="section-body"><div className="ai-card"><div className="ai-label"><Sparkles size={12}/>AI investigation · {Math.round((exception.aiConfidence??0)*100)}%</div><h3>{statusLabel(exception.category)}</h3><p>{exception.aiAnalysis}</p><div className="recommend"><strong>Suggested next step</strong><br/>{exception.aiRecommendation}</div></div><div className="action-row"><button className="btn btn-primary" disabled={!canDecide} title={canDecide?"":"Manager permission required"} onClick={()=>decide("APPROVED","Approved")}><Check size={14}/>Approve with justification</button><button className="btn" disabled={!canDecide} onClick={()=>decide("EXCEPTION","Request info")}><FileSearch size={14}/>Request info</button><button className="btn btn-danger" disabled={!canDecide} onClick={()=>decide("REJECTED","Rejected")}><X size={14}/>Reject</button></div>{!canDecide&&<p style={{fontSize:9,color:"#87918d",textAlign:"center"}}>Switch to AP Manager to make a decision.</p>}</div></div>}
      <div className="card"><div className="panel-head"><h2>Immutable audit trail</h2><ShieldCheck size={14} color="#176b51"/></div><div className="section-body audit">{audits.map(a=><div className="audit-item" key={a.id}><strong>{statusLabel(a.action)}</strong><span>{new Date(a.createdAt).toLocaleString("en-GB")} · {a.userId?"Human decision":"System"}</span></div>)}</div></div>
    </div></>;
}

function Field({label,value,confidence}:{label:string;value:string;confidence:number}) { return <div className="field"><div><label>{label}</label><strong>{value}</strong></div><span className={`confidence ${confidence<.75?"low":""}`}>{Math.round(confidence*100)}%</span></div> }

function Rules({rules,role,updateRule,onSave}:{rules:RulesConfig;role:Role;updateRule:(k:keyof RulesConfig,v:number|boolean)=>void;onSave:()=>void}) { const disabled=role==="AUDITOR"||role==="AP_CLERK"; return <><div className="page-head"><div><div className="eyebrow">Governance · Version 3 active</div><h1>Rules & controls</h1><p className="subtitle">Deterministic thresholds applied before any AI recommendation.</p></div><button className="btn btn-primary" disabled={disabled} onClick={onSave}><FileCheck2 size={14}/>Save as version 4</button></div><div className="card"><div className="panel-head"><h2>Three-way matching tolerances</h2><span>Changes apply to new processing runs</span></div><Rule title="Unit price variance" text="Maximum invoice price difference from the approved PO line." value={rules.priceTolerancePercent} suffix="%" disabled={disabled} set={v=>updateRule("priceTolerancePercent",v)}/><Rule title="Quantity variance" text="Maximum invoiced quantity difference from goods received." value={rules.quantityTolerancePercent} suffix="%" disabled={disabled} set={v=>updateRule("quantityTolerancePercent",v)}/><Rule title="Invoice total variance" text="Maximum total difference before routing to manager review." value={rules.totalTolerancePercent} suffix="%" disabled={disabled} set={v=>updateRule("totalTolerancePercent",v)}/><Rule title="Auto-approval ceiling" text="Invoices above this value always require a human approval." value={rules.autoApprovalLimit} suffix="QAR" disabled={disabled} set={v=>updateRule("autoApprovalLimit",v)}/><Rule title="Duplicate lookback" text="Date window used for fuzzy duplicate detection." value={rules.duplicateDateWindowDays} suffix="days" disabled={disabled} set={v=>updateRule("duplicateDateWindowDays",v)}/><div className="rule-row"><div><h3>Require goods receipt</h3><p>Block auto-processing when no GRN exists for a referenced purchase order.</p></div><button className="toggle" disabled={disabled} aria-label="Require goods receipt" onClick={()=>updateRule("requireGrn",!rules.requireGrn)}/></div></div><div className="card" style={{marginTop:16,padding:17,display:"flex",gap:12,alignItems:"center"}}><Bot size={18} color="#176b51"/><div><strong style={{fontSize:11.5}}>Governance boundary</strong><p style={{fontSize:10,color:"#66736e",margin:"3px 0 0"}}>AI explains exceptions but cannot change these rules or apply a financial decision.</p></div></div></> }
function Rule({title,text,value,suffix,disabled,set}:{title:string;text:string;value:number;suffix:string;disabled:boolean;set:(n:number)=>void}) { return <div className="rule-row"><div><h3>{title}</h3><p>{text}</p></div><div className="rule-control"><input className="input" disabled={disabled} type="number" value={value} onChange={e=>set(Number(e.target.value))}/><span style={{fontSize:10,color:"#66736e"}}>{suffix}</span></div></div> }
function Empty() { return <div className="empty"><span className="empty-icon"><Inbox size={18}/></span><h3>No invoices found</h3><p>Try adjusting your search or status filter.</p></div> }

function UploadDialog({stage,fileName,onClose,onFile}:{stage:number;fileName:string;onClose:()=>void;onFile:(file:File)=>void}) { const stages=["Received","Extracting fields","Validating supplier","Matching PO & GRN","Decision ready"]; return <div className="modal-backdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="upload-title"><div className="modal-head"><div><div className="eyebrow">New intake</div><h2 id="upload-title">Process an invoice</h2></div><button className="icon-btn" aria-label="Close upload" onClick={onClose} disabled={stage>=0}><X size={15}/></button></div>{stage<0?<label className="dropzone"><Upload size={25}/><strong>Drop an invoice here or browse</strong><span>PDF, PNG or JPG · up to 10 MB · Arabic and English</span><input type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(file)onFile(file)}}/></label>:<div className="processing"><div className="file-chip"><FileCheck2 size={18}/><div><strong>{fileName}</strong><span>Secure local intake</span></div></div><div className="processing-list">{stages.map((label,i)=><div className={`processing-step ${i<stage?"done":i===stage?"active":""}`} key={label}><span>{i<stage?<Check size={12}/>:i+1}</span><strong>{label}</strong>{i===stage&&<i/>}</div>)}</div><p>Deterministic controls are applied before any AI recommendation.</p></div>}</div></div> }
